---
  - name: Creatnge a new database
    mysql_db:
      name: wordpress
      state: present
      login_user: wordpress
      login_password: "wordpress"

  - name: Setuping mysql slave config
    template:
      src: templates/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf

  - name: Configuring replication on the slave
    mysql_replication:
      mode: changemaster
      master_host: 192.168.100.101
      master_user: wordpress
      master_password: "wordpress"
      master_log_file: mysql-bin.000001
      master_log_pos: 157

  - name: Reloading mysql
    service:
      name: mysql
      state: restarted
      enabled: true

  - name: Reseting replica
    mysql_replication: 
      mode: resetslave

  - name: Starting replica
    mysql_replication:
      mode: startslave

